//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkyaWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingEntities1 : DbContext
    {
        public TestingEntities1()
            : base("name=TestingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_city> sys_city { get; set; }
        public virtual DbSet<sys_country> sys_country { get; set; }
        public virtual DbSet<sys_login> sys_login { get; set; }
        public virtual DbSet<sys_retail> sys_retail { get; set; }
        public virtual DbSet<sys_retail2Images> sys_retail2Images { get; set; }
        public virtual DbSet<sys_roles> sys_roles { get; set; }
        public virtual DbSet<sys_state> sys_state { get; set; }
    }
}
